services:
  loftools:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    restart: unless-stopped
    networks:
      - popcornbowl

networks:
  popcornbowl:
    external: true
