services:
  valuetools:
    container_name: loftools
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    restart: unless-stopped
    networks:
      - popcornbowl
    labels:
      - "swag=enable"
      - "swag_port=80"

networks:
  popcornbowl:
    external: true
